# Generated by Django 4.2.7 on 2024-10-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_app', '0005_jobapplication_job_user_delete_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
