# Generated by Django 4.2.7 on 2024-10-08 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ats_app', '0006_alter_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ats_app.user'),
            preserve_default=False,
        ),
    ]
