# Generated by Django 4.2.7 on 2024-10-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ats_app', '0008_jobapplication_job_alter_job_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
    ]
