# Generated by Django 4.2.7 on 2024-11-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_app', '0011_alter_profile_education_alter_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_new_user',
            field=models.BooleanField(default=True),
        ),
    ]
