# Generated by Django 5.0.7 on 2024-11-07 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_app', '0013_jobapplication_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='ats_app.job'),
        ),
    ]
