# Generated by Django 5.0.7 on 2024-11-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ats_app', '0014_alter_jobapplication_job'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
    ]
