# Generated by Django 5.0.7 on 2024-11-07 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_app', '0015_alter_jobapplication_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ats_app.job'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='unique_job_application'),
        ),
    ]
