# Generated by Django 5.0.7 on 2024-11-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ats_app', '0016_jobapplication_job_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='last_name',
        ),
    ]
